# Generated by Django 5.0.1 on 2024-01-07 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Creator', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('usr_name', models.CharField(max_length=50, null=True)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('password', models.CharField(max_length=50)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='UserPictures/Profile')),
                ('bannerimage', models.ImageField(blank=True, null=True, upload_to='UserPictures/Banner')),
                ('date_joined', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='FollowCr',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_followed', models.DateTimeField(auto_now_add=True)),
                ('following', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followed_Creator', to='Creator.creators')),
                ('follower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following_User', to='User.formuser')),
            ],
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('PlaylistName', models.CharField(max_length=50)),
                ('Playlist_Cover', models.ImageField(blank=True, null=True, upload_to='User/Playlist')),
                ('UsrId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.formuser')),
            ],
        ),
        migrations.CreateModel(
            name='PlaylistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MusicId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Creator.music')),
                ('Plid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.playlist')),
            ],
        ),
    ]
